//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/ControlMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlMap"",
    ""maps"": [
        {
            ""name"": ""JetEngine"",
            ""id"": ""cfed0506-cf36-42c5-8ee4-dc273547e37b"",
            ""actions"": [
                {
                    ""name"": ""ThrottleUp"",
                    ""type"": ""Button"",
                    ""id"": ""88ddfbc5-a03f-41e5-b39f-23212d0ea5f7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrottleDown"",
                    ""type"": ""Button"",
                    ""id"": ""3e220b57-a53b-4fef-b5cb-4c44ba1b481a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrottleStepUp"",
                    ""type"": ""Button"",
                    ""id"": ""506d690e-bcdc-4cf5-a041-05a685579042"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrottleStepDown"",
                    ""type"": ""Button"",
                    ""id"": ""577a78f4-a6c8-420d-8a5f-4d91ea7ef2d2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleAB"",
                    ""type"": ""Button"",
                    ""id"": ""c2b883c5-7a69-42f9-8609-67f6f0feafc2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3ca9a66c-d279-437e-adbc-02e6b2b2f588"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77ac7bf7-fb8a-462c-8de8-0005e17da461"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6b21620-4150-42c2-aa68-6cdfd7eb80ba"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleStepUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39eff000-1088-4096-a43d-e6b3c4899caa"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleStepDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24921f61-2e77-4711-9084-e73661e73fe4"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleAB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // JetEngine
        m_JetEngine = asset.FindActionMap("JetEngine", throwIfNotFound: true);
        m_JetEngine_ThrottleUp = m_JetEngine.FindAction("ThrottleUp", throwIfNotFound: true);
        m_JetEngine_ThrottleDown = m_JetEngine.FindAction("ThrottleDown", throwIfNotFound: true);
        m_JetEngine_ThrottleStepUp = m_JetEngine.FindAction("ThrottleStepUp", throwIfNotFound: true);
        m_JetEngine_ThrottleStepDown = m_JetEngine.FindAction("ThrottleStepDown", throwIfNotFound: true);
        m_JetEngine_ToggleAB = m_JetEngine.FindAction("ToggleAB", throwIfNotFound: true);
    }

    ~@ControlMap()
    {
        UnityEngine.Debug.Assert(!m_JetEngine.enabled, "This will cause a leak and performance issues, ControlMap.JetEngine.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // JetEngine
    private readonly InputActionMap m_JetEngine;
    private List<IJetEngineActions> m_JetEngineActionsCallbackInterfaces = new List<IJetEngineActions>();
    private readonly InputAction m_JetEngine_ThrottleUp;
    private readonly InputAction m_JetEngine_ThrottleDown;
    private readonly InputAction m_JetEngine_ThrottleStepUp;
    private readonly InputAction m_JetEngine_ThrottleStepDown;
    private readonly InputAction m_JetEngine_ToggleAB;
    public struct JetEngineActions
    {
        private @ControlMap m_Wrapper;
        public JetEngineActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @ThrottleUp => m_Wrapper.m_JetEngine_ThrottleUp;
        public InputAction @ThrottleDown => m_Wrapper.m_JetEngine_ThrottleDown;
        public InputAction @ThrottleStepUp => m_Wrapper.m_JetEngine_ThrottleStepUp;
        public InputAction @ThrottleStepDown => m_Wrapper.m_JetEngine_ThrottleStepDown;
        public InputAction @ToggleAB => m_Wrapper.m_JetEngine_ToggleAB;
        public InputActionMap Get() { return m_Wrapper.m_JetEngine; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(JetEngineActions set) { return set.Get(); }
        public void AddCallbacks(IJetEngineActions instance)
        {
            if (instance == null || m_Wrapper.m_JetEngineActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_JetEngineActionsCallbackInterfaces.Add(instance);
            @ThrottleUp.started += instance.OnThrottleUp;
            @ThrottleUp.performed += instance.OnThrottleUp;
            @ThrottleUp.canceled += instance.OnThrottleUp;
            @ThrottleDown.started += instance.OnThrottleDown;
            @ThrottleDown.performed += instance.OnThrottleDown;
            @ThrottleDown.canceled += instance.OnThrottleDown;
            @ThrottleStepUp.started += instance.OnThrottleStepUp;
            @ThrottleStepUp.performed += instance.OnThrottleStepUp;
            @ThrottleStepUp.canceled += instance.OnThrottleStepUp;
            @ThrottleStepDown.started += instance.OnThrottleStepDown;
            @ThrottleStepDown.performed += instance.OnThrottleStepDown;
            @ThrottleStepDown.canceled += instance.OnThrottleStepDown;
            @ToggleAB.started += instance.OnToggleAB;
            @ToggleAB.performed += instance.OnToggleAB;
            @ToggleAB.canceled += instance.OnToggleAB;
        }

        private void UnregisterCallbacks(IJetEngineActions instance)
        {
            @ThrottleUp.started -= instance.OnThrottleUp;
            @ThrottleUp.performed -= instance.OnThrottleUp;
            @ThrottleUp.canceled -= instance.OnThrottleUp;
            @ThrottleDown.started -= instance.OnThrottleDown;
            @ThrottleDown.performed -= instance.OnThrottleDown;
            @ThrottleDown.canceled -= instance.OnThrottleDown;
            @ThrottleStepUp.started -= instance.OnThrottleStepUp;
            @ThrottleStepUp.performed -= instance.OnThrottleStepUp;
            @ThrottleStepUp.canceled -= instance.OnThrottleStepUp;
            @ThrottleStepDown.started -= instance.OnThrottleStepDown;
            @ThrottleStepDown.performed -= instance.OnThrottleStepDown;
            @ThrottleStepDown.canceled -= instance.OnThrottleStepDown;
            @ToggleAB.started -= instance.OnToggleAB;
            @ToggleAB.performed -= instance.OnToggleAB;
            @ToggleAB.canceled -= instance.OnToggleAB;
        }

        public void RemoveCallbacks(IJetEngineActions instance)
        {
            if (m_Wrapper.m_JetEngineActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IJetEngineActions instance)
        {
            foreach (var item in m_Wrapper.m_JetEngineActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_JetEngineActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public JetEngineActions @JetEngine => new JetEngineActions(this);
    public interface IJetEngineActions
    {
        void OnThrottleUp(InputAction.CallbackContext context);
        void OnThrottleDown(InputAction.CallbackContext context);
        void OnThrottleStepUp(InputAction.CallbackContext context);
        void OnThrottleStepDown(InputAction.CallbackContext context);
        void OnToggleAB(InputAction.CallbackContext context);
    }
}
